const participants = [
  {
    name: "Andrea",
    birthday: "13 Agosto / 2026",
    status: "Pendiente",
    goal: 1500000,
    monthlyFee: 125000,
    initialPercentPaid: true,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 125000,
        paid: 125000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Bibian",
    birthday: "25 Mayo / 2027",
    status: "Pendiente",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: true,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Brayan",
    birthday: "20 Septiembre / 2026",
    status: "Al día",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: true,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Demri",
    birthday: "15 Julio / 2026",
    status: "Pendiente",
    goal: 1500000,
    monthlyFee: 125000,
    initialPercentPaid: true,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 125000,
        paid: 125000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Fabián",
    birthday: "18 Diciembre / 2026",
    status: "Pendiente",
    goal: 1500000,
    monthlyFee: 125000,
    initialPercentPaid: true,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 125000,
        paid: 125000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Geraldine",
    birthday: "8 Noviembre / 2026",
    status: "Pendiente",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: true,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Hugo",
    birthday: "6 Septiembre / 2026",
    status: "Pendiente",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: false,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Inés",
    birthday: "28 Enero / 2027",
    status: "Pendiente",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: true,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Julián",
    birthday: "1 Abril / 2027",
    status: "Al día",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: true,
    progress: 1,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },

  {
    name: "Marinita",
    birthday: "14 Mayo / 2027",
    status: "Pendiente",
    goal: 1500000,
    monthlyFee: 125000,
    initialPercentPaid: true,
    progress: 1,

    payments: [
      {
        month: "Abril",
        fee: 125000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Mathías",
    birthday: "18 Agosto / 2026",
    status: "Pendiente",
    goal: 3000000,
    monthlyFee: 250000,
    initialPercentPaid: true,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 250000,
        paid: 250000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Nancy",
    birthday: "28 Marzo / 2027",
    status: "Pendiente",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: true,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Naty",
    birthday: "2 Febrero / 2027",
    status: "Al día",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: true,
    progress: 0.08,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Nicolás",
    birthday: "24 Abril / 2027",
    status: "Al día",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: true,
    progress: 0,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },

  /*{
    name: "Nicole",
    birthday: "26 Mayo / 2027",
    status: "Pendiente",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: false,
    progress: 0,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },*/

  {
    name: "Óscar",
    birthday: "5 Abril / 2027",
    status: "Pendiente",
    goal: 1800000,
    monthlyFee: 150000,
    initialPercentPaid: true,
    progress: 0.8,

    payments: [
      {
        month: "Abril",
        fee: 150000,
        paid: 150000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 150000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Peter",
    birthday: "9 Septiembre / 2026",
    status: "Al día",
    goal: 3000000,
    monthlyFee: 250000,
    initialPercentPaid: true,
    progress: 0.8,

    payments: [
      {
        month: "Abril",
        fee: 250000,
        paid: 250000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 250000,
        paid: 250000,
        status: "Pagado",
      },
      {
        month: "Junio",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Tere",
    birthday: "23 Septiembre / 2026",
    status: "Pendiente",
    goal: 1500000,
    monthlyFee: 125000,
    initialPercentPaid: true,
    progress: 0.8,

    payments: [
      {
        month: "Abril",
        fee: 125000,
        paid: 125000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Teresita",
    birthday: "13 Octubre / 2026",
    status: "Pendiente",
    goal: 1500000,
    monthlyFee: 125000,
    initialPercentPaid: true,
    progress: 0.8,

    payments: [
      {
        month: "Abril",
        fee: 125000,
        paid: 125000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 125000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Thomas",
    birthday: "22 Noviembre / 2026",
    status: "Pendiente",
    goal: 3000000,
    monthlyFee: 250000,
    initialPercentPaid: true,
    progress: 0.8,

    payments: [
      {
        month: "Abril",
        fee: 250000,
        paid: 250000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Valery",
    birthday: "11 Julio / 2026",
    status: "Pendiente",
    goal: 3000000,
    monthlyFee: 250000,
    initialPercentPaid: true,
    progress: 0.8,

    payments: [
      {
        month: "Abril",
        fee: 250000,
        paid: 250000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Junio",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
  {
    name: "Yaz",
    birthday: "24 Enero / 2027",
    status: "Al día",
    goal: 3000000,
    monthlyFee: 250000,
    initialPercentPaid: true,
    progress: 0.8,

    payments: [
      {
        month: "Abril",
        fee: 250000,
        paid: 250000,
        status: "Pagado",
      },
      {
        month: "Mayo",
        fee: 250000,
        paid: 250000,
        status: "Pagado",
      },
      {
        month: "Junio",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Julio",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Agosto",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Septiembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Octubre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Noviembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Diciembre",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Enero",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Febrero",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
      {
        month: "Marzo",
        fee: 250000,
        paid: 0,
        status: "Próximo",
      },
    ],
  },
];

//ENTREGA DE REGALOS

const deliveredGifts = [
   /*{
    name: "Valery",
    date: "11 Julio / 2026",
    amount: 3000000,
  },*/

  /*{
    name: "Demri",
    date: "15 Julio / 2026",
    amount: 1500000,
  },*/

  /*{
    name: "Andrea",
    date: "13 Agosto / 2026",
    amount: 1500000,
  },*/

  /*{
    name: "Mathías",
    date: "18 Agosto / 2026",
    amount: 3000000,
  },*/

  /*{
    name: "Hugo",
    date: "6 Septiembre / 2026",
    amount: 1800000,
  },*/
];